# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb2ad62a6d4c0c9b940f0577a5f3e1756d93cda582696b870a76497709fd40c496fd75f017f60284e7d5f2e3088b087aa67918e8d5428ce991e40093cabdf210

test:
  secret_key_base: b343e48d85d3a96cb9d07cec0f6955b641ece2a26a38e52817f978c8d9670ace8a43cbd5d9cc6440a6a86e0f20ee380b19efc7aac94f70217cfe7161645f2adb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
